-- Bước 1: Chuyển container về XEPDB1
ALTER SESSION SET CONTAINER = XEPDB1;

-- Bước 2: Xóa các đối tượng tồn tại
-- Xóa các public synonym nếu đã tồn tại
BEGIN
  FOR s IN (
    SELECT synonym_name FROM all_synonyms -- Use all_synonyms as it shows public ones too
    WHERE owner = 'PUBLIC' AND table_owner = 'ADMIN' AND synonym_name IN (
      'DONVI','NHANVIEN','SINHVIEN','HOCPHAN','MOMON','DANGKY',
      'VW_NHANVIEN_NVCB', 'VW_NHANVIEN_TRGDV', 
      'VW_MOMON_GV', 'VW_DANGKY_GV', 'VW_MOMON_TRGDV', 'VW_MOMON_SV', 'VW_MOMON_PDT'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM ' || s.synonym_name;
  END LOOP;
END;
/

-- Xóa các bảng
BEGIN
  FOR t IN (
    SELECT table_name FROM all_tables
    WHERE owner = 'ADMIN' AND table_name IN ('DANGKY','MOMON','HOCPHAN','SINHVIEN','NHANVIEN','DONVI')
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

-- Xóa các view
BEGIN
  FOR v IN (
    SELECT view_name FROM all_views
    WHERE owner = 'ADMIN' AND (view_name LIKE 'VW_NHANVIEN_%' OR view_name LIKE 'VW_MOMON_%' OR view_name LIKE 'VW_DANGKY_%')
  ) LOOP
    EXECUTE IMMEDIATE 'DROP VIEW ADMIN.' || v.view_name;
  END LOOP;
END;
/

-- Xóa các role
BEGIN
  FOR r IN (
    SELECT role FROM dba_roles
    WHERE role IN ('ROLE_NVCB', 'ROLE_TRGDV', 'ROLE_TCHC', 'ROLE_GV', 'ROLE_SV', 'ROLE_NV_PDT', 'ROLE_NV_PCTSV', 'ROLE_NV_PKT')
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP ROLE ' || r.role;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/

-- Xóa các user
BEGIN
  FOR u IN (
    SELECT username FROM dba_users
    WHERE username IN ('GV001', 'GV002', 'NV001', 'NV002', 'NV003', 'CB001', 'NV004', 'SV001', 'SV002')
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP USER ' || u.username || ' CASCADE';
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/

-- Bước 3: Kết nối với tài khoản ADMIN

CREATE USER ADMIN IDENTIFIED BY admin
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;
  
-- Bước 4: Tạo các bảng

CREATE TABLE ADMIN.DONVI (MAĐV VARCHAR2(10) PRIMARY KEY, TENĐV VARCHAR2(100), LOAIĐV VARCHAR2(10) CHECK (LOAIĐV IN ('Khoa', 'Phòng')), TRGĐV VARCHAR2(10));
CREATE TABLE ADMIN.NHANVIEN (MANV VARCHAR2(10) PRIMARY KEY, HOTEN VARCHAR2(100), PHAI CHAR(1) CHECK (PHAI IN ('M', 'F')), NGSINH DATE, LUONG NUMBER(10,2), PHUCAP NUMBER(10,2), ĐT VARCHAR2(15), VAITRO VARCHAR2(20), MAĐV VARCHAR2(10), FOREIGN KEY (MAĐV) REFERENCES ADMIN.DONVI(MAĐV));
ALTER TABLE ADMIN.DONVI ADD CONSTRAINT fk_donvi_trgdv FOREIGN KEY (TRGĐV) REFERENCES ADMIN.NHANVIEN(MANV);
CREATE TABLE ADMIN.SINHVIEN (MASV VARCHAR2(10) PRIMARY KEY, HOTEN VARCHAR2(100), PHAI CHAR(1), NGSINH DATE, ĐCHI VARCHAR2(200), ĐT VARCHAR2(15), KHOA VARCHAR2(10), TINHTRANG VARCHAR2(20), FOREIGN KEY (KHOA) REFERENCES ADMIN.DONVI(MAĐV));
CREATE TABLE ADMIN.HOCPHAN (MAHP VARCHAR2(10) PRIMARY KEY, TENHP VARCHAR2(100), SOTC NUMBER, STLT NUMBER, STTH NUMBER, MAĐV VARCHAR2(10), FOREIGN KEY (MAĐV) REFERENCES ADMIN.DONVI(MAĐV));
CREATE TABLE ADMIN.MOMON (MAMM VARCHAR2(10) PRIMARY KEY, MAHP VARCHAR2(10), MAGV VARCHAR2(10), HK NUMBER(1), NAM NUMBER(4), FOREIGN KEY (MAHP) REFERENCES ADMIN.HOCPHAN(MAHP), FOREIGN KEY (MAGV) REFERENCES ADMIN.NHANVIEN(MANV));
CREATE TABLE ADMIN.DANGKY (MASV VARCHAR2(10), MAMM VARCHAR2(10), ĐIEMTH NUMBER(5,2), ĐIEMQT NUMBER(5,2), ĐIEMCK NUMBER(5,2), ĐIEMTK NUMBER(5,2), PRIMARY KEY (MASV, MAMM), FOREIGN KEY (MASV) REFERENCES ADMIN.SINHVIEN(MASV), FOREIGN KEY (MAMM) REFERENCES ADMIN.MOMON(MAMM));
